### ISSUE TITLE
Worksheets test and Tables From Types tests fail

### ISSUE THREAD

**Issue by johncj-improving** [misterspeedy/FsExcel#10]
The worksheet test failed because it was looking for a tab named "English (United Kingdom)" and the actual worksheet created on my machine was named according to my local culture "English (United States)". 

The tables from types test failed when comparing the DateJoined values with this error:
Expected: 2022-03-12T00:00:00.0000000
Actual: 2022-03-11T18:00:00.0000000

(My offset from UTC is -6).

I will create a PR to fix these issues.

**Comment by misterspeedy** [comment]
Closed with many thanks for the PR!
