### ISSUE TITLE
More problems with tests

### ISSUE THREAD

**Issue by johncj-improving** [misterspeedy/FsExcel#12]
As I was working on a PR for Issue #9, I realized that there a problem with all of the tests that use `CultureInfo.CurrentCulture.DateTimeFormat.GetMonthName`.

Those tests will obviously fail on any system that does use the English names for the months. The quickest and most obvious solution is to change all those calls to `CultureInfo.GetCultureInfoByIetfLanguageTag("en-GB").DateTimeFormat.GetMonthName`. I'd be willing to do a PR that's acceptable. However, I thought I should ask if you want to take a different approach.

**Comment by misterspeedy** [comment]
That sounds like a sensible approach. For these silly mistakes of mine, please feel free to dive straight in with a PR if you'd prefer.  Thanks again so much for the input!

**Comment by johncj-improving** [comment]
This is resolved with my last PR.
