### ISSUE TITLE
Feature Proposal: InsertRowsAbove

### ISSUE THREAD

**Issue by johncj-improving** [misterspeedy/FsExcel#16]
When working with an existing worksheet, I've found that very often the safest way to add data is to insert rows above the existing data in the worksheet. I'd like to add a case `| InsertRowsAbove of int' to the Item DU. This would insert some number of rows above the current row index. 

(I know ClosedXML also has an InsertRowsBelow method. I'd prefer to keep the API as simple possible and simply suggest to users that adding one to the row index and then calling InsertRowsAbove is the same thing as InsertRowsBelow)

**Comment by misterspeedy** [comment]
Seems like a great idea! Another one I hadn't even considered.
