### ISSUE TITLE
Consider supporting NetStandard 2.0 etc.

### ISSUE THREAD

**Issue by isaacabraham** [misterspeedy/FsExcel#6]
Currently the package only (seems) to support .NET 5. Supporting .NET Standard 2.0 would allow other .NET runtimes to use this package e.g. .NET Core 3.1, Net Framework 4.8 etc. I *think* .NET 6 should be ok though.

**Comment by misterspeedy** [comment]
Good point, thanks - I'll look into it.

**Comment by misterspeedy** [comment]
Changed to target NetStandard2.1. Version 0.0.30.
